#database properties 
spring.application.name=department-service
spring.datasource.url=jdbc:postgresql://localhost:5432/department_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver=org.postgresql.Driver


#hibernate propertes
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register with Eureka
eureka.client.register-with-eureka=true

# Fetch Registry from Eureka
eureka.client.fetch-registry=true

# Register using IP Address
eureka.instance.prefer-ip-address=true

# Unique Instance ID

eureka.instance.instance-id=${spring.application.name}:${server.port}
